#!/usr/bin/env python3
import os

os.chdir(os.path.dirname(os.path.realpath(__file__)))

from src.core.runtime import run
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("projects",
            help="one or more projects to be run")
    parser.add_argument('start', type=str)
    parser.add_argument('end', type=str)
    parser.add_argument("-w","--wrap",
            help="specify that projects should be run in 'wrapped' mode",
            action='store_true')
    args = parser.parse_args()
    return vars(args)

def main():
    args = parse_args()
    run(proj=args['projects'],start_time=args['start'],end_time=args['end'],wrap=args['wrap'])

if __name__ == '__main__':
    main()
